# Generated by Django 4.0 on 2021-12-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
